from google import genai
from google.genai import types
import os
import sys

project_id = os.getenv("GOOGLE_CLOUD_PROJECT", "uppdemos")
client = genai.Client(vertexai=True, project=project_id, location="global")

img_path = '/Users/upasanapati/shrinkAI experiment/Antigravity_Experiments/UP_Demos/translation-v3/debug_images/page_0_image_28.png'

if not os.path.exists(img_path):
    print(f"File not found: {img_path}")
    sys.exit(1)

with open(img_path, "rb") as f:
    img_bytes = f.read()

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=[
        types.Part.from_bytes(data=img_bytes, mime_type="image/png"),
        "Look at this image. It is a chart generated by an AI translation pipeline. Determine if the text labels in the chart are in English or German. List some of the labels to prove it."
    ]
)

print("Transcription/Inspection Result:")
print(response.text)
