-- 1. Create Placeholder Tables If They Do Not Exist
-- (Using CreateNotebook schema to safely establish an empty Struct partition to query against without breaking the view file compilation)

CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}search.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}assist.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}streamassist.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}answerquery.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}createengine.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}updateengine.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}setiampolicy.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}createagent.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}updateagent.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}createagentrequest.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}generategroundedcontent.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}updatedataconnector.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}addcontextfile.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}uploadsessionfile.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;
CREATE TABLE IF NOT EXISTS `${PROJECT_ID}.${GE_DATASET_PREFIX}writeuserevent.discoveryengine_googleapis_com_gemini_enterprise_user_activity` PARTITION BY DATE(timestamp) AS SELECT * FROM `${PROJECT_ID}.nlm_raw_logs_createnotebook.discoveryengine_googleapis_com_gemini_enterprise_user_activity` LIMIT 0;

CREATE OR REPLACE VIEW `${PROJECT_ID}.${GE_TRANSFORMED_DATASET}.ge_logs` AS

SELECT
  SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request,
  SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response,
  JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel,
  JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName,
  JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal,
  
  -- Coalesce accessors for varying payload formats
  COALESCE(
    JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'),
    JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')
  ) AS userQuery,
  
  JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply,
  
  COALESCE(
    JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'),
    JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')
  ) AS serviceAttributionToken,
  
  JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName,
  REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id,
  REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id,
  
  COALESCE(
    REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'),
    REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')
  ) AS engine_id,
  timestamp
FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}search.discoveryengine_googleapis_com_gemini_enterprise_user_activity`

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}assist.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}streamassist.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}answerquery.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}createengine.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}updateengine.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}setiampolicy.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}createagent.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}updateagent.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}createagentrequest.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}generategroundedcontent.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}updatedataconnector.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}addcontextfile.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)

UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}uploadsessionfile.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
UNION ALL

SELECT SAFE_CAST(request AS JSON), SAFE_CAST(response AS JSON), serviceLabel, methodName, userIamPrincipal, userQuery, serviceTextReply, serviceAttributionToken, serviceName, session_id, answer_id, engine_id, timestamp FROM (
  SELECT SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.request')) AS request, SAFE.PARSE_JSON(JSON_QUERY(TO_JSON_STRING(jsonPayload), '$.response')) AS response, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicelabel') AS serviceLabel, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.methodname') AS methodName, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.useriamprincipal') AS userIamPrincipal, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query.parts[0].text'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.query')) AS userQuery, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.servicetextreply') AS serviceTextReply, COALESCE(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.assisttoken'), JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.attributiontoken')) AS serviceAttributionToken, JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.logmetadata.servicename') AS serviceName, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/sessions/([^/]+)') AS session_id, REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.response.answer.name'), r'/assistAnswers/([^/]+)') AS answer_id, COALESCE(REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.name'), r'/engines/([^/]+)'), REGEXP_EXTRACT(JSON_VALUE(TO_JSON_STRING(jsonPayload), '$.request.servingconfig'), r'/engines/([^/]+)')) AS engine_id, timestamp FROM `${PROJECT_ID}.${GE_DATASET_PREFIX}writeuserevent.discoveryengine_googleapis_com_gemini_enterprise_user_activity`
)
);
